fix: Segmentation mask output datatype to int
chanzuckerberg/cryoet-data-portal-backend pull request #170
Opened 2024-07-25 20:07 UTC by manasaV3

Relates to

## Description
Fixes the issue of segmentation mask output being a float. The [converter selection](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/66e0ddc0cffdafe8b0d71d678b7443a585337ca2/ingestion_tools/scripts/common/image.py#L418) is determined by if the label is `None`.

2024-07-25 20:09 UTC, jgadling commented
Note: at some point a test would be nice

2024-07-25 20:12 UTC, manasaV3 commented
> Note: at some point a test would be nice

I agree. I think in addition to this being unit test, this is something we should add to our s3 validation. cc: @daniel-ji

2024-07-25 20:23 UTC, uermel requested changes
This does not seem to fix the issue. To clarify, I am actually setting the mask_label in the config here: 

https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/f6e180988e670430768a6e0813f52b74acd6f53a/ingestion_tools/dataset_configs/10436.yaml#L103

2024-07-25 20:57 UTC, uermel commented
Found the bug: 

`TomoConverter.scaled_data_transformation` also has to be applied to the base layer of the pyramid here: https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/66e0ddc0cffdafe8b0d71d678b7443a585337ca2/ingestion_tools/scripts/common/image.py#L273

i.e. change to 

`pyramid = [self.scaled_data_transformation(self.volume_reader.get_pyramid_base_data())]`

2024-07-26 15:44 UTC, uermel approved these changes

2024-07-31 19:25 UTC, merged