Adding ER Diagrams to schema/api
chanzuckerberg/cryoet-data-portal-backend pull request #214
Opened 2024-08-22 02:36 UTC by manasaV3

Relates to

## Description
Adds ER diagram generation to the make command, such that the er diagram will be updated to reflect the changes to api schema. 

The dataset is set as root of the diagram, to help maintain consistency between different versions of the diagram.

2024-08-22 23:40 UTC, daniel-ji requested changes

2024-08-22 23:40 UTC, daniel-ji commented on schema/Makefile
> +# To build-ingestion-config for the non-default version, run `make build-api $INGESTION_CONFIG_VERSION=2.0.0 CORE_VERSION=2.0.0`
```
# To build-ingestion-config for the non-default version, run `make build-ingestion-config INGESTION_CONFIG_VERSION=v2.0.0 CORE_VERSION=v2.0.0`
```

2024-08-22 23:40 UTC, daniel-ji commented on schema/Makefile
> +.PHONY: build-api
Should it be `make build-api API_VERSION=v2.0.0 CORE_VERSION=v2.0.0`?

2024-08-22 23:40 UTC, daniel-ji commented on schema/Makefile
> +	# Hardcoding these while we wait for an upstream LinkML bug to be fixed: https://github.com/linkml/linkml-runtime/pull/330
is this comment still needed?

2024-08-23 17:38 UTC, manasaV3 commented on schema/Makefile
> +	# Hardcoding these while we wait for an upstream LinkML bug to be fixed: https://github.com/linkml/linkml-runtime/pull/330
I believe not..

2024-08-23 20:34 UTC, jgadling approved these changes

2024-08-26 17:28 UTC, daniel-ji approved these changes
looks good to me!

2024-08-26 17:28 UTC, merged